config/routes.rb
RentACat::Application.routes.draw do
  resources :cats
  resource :user
  resource :session
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  CAT_COLORS = %w{black gray white brown orange}

  validates :name, presence: true

  validates_numericality_of :age

  validate :color, inclusion: { in: CAT_COLORS,
    message: "%{value} is not a recognized color" }

  validates :sex, inclusion: { in: %w(M F),
    message: "%{value} is not a recognized sex" }
    
  # leaving these out, so bootstrapping the database is possible
  # validates :user_id, numericality: { only_integer: true }
  # validate :user_id, inclusion: { in: [User.find_by_id(:user_id)],
  #   message: "%{value} is not a valid user id" }
    
  # actual test: 
  validates :user, presence: true

  has_many :cat_rental_requests
  belongs_to :user
  
  def self.colors
    CAT_COLORS
  end
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  STATUSES = %w{ PENDING APPROVED DENIED}
  
  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, inclusion: { in: STATUSES,
    message: "%{value} is not a recognized request status"}
  validate :overlapping_approved_requests
  
  belongs_to :cat
  
  def overlapping_requests
    # sort start dates and end dates together, and look for two in a row, 
    # start or end? 
    # go over requests. 
    # compare every request to current request: 
    # req: certain cat, and APPROVED
    # CatRentalRequest.instance.execute
    
    query = <<-SQL
    cat_rental_requests.id != :id AND (
      ((:start) BETWEEN cat_rental_requests.start_date AND cat_rental_requests.end_date)
    OR
      ((:end) BETWEEN cat_rental_requests.start_date AND cat_rental_requests.end_date)
    OR
      (cat_rental_requests.start_date BETWEEN :start AND :end)
    OR
      (cat_rental_requests.end_date BETWEEN :start AND :end))
    SQL
    self.cat.cat_rental_requests.where(query, id: self.id,
      :start => start_date, 
      :end => end_date
    ) 
    # does return self, btw. 
  end
  
  def overlapping_approved_requests
    # debugger
    overlap = overlapping_requests.where(status: "APPROVED")#"status = 'APPROVED'")
    return true if overlap.length == 0
    p overlap.to_a
    previously = overlap.select("start_date, end_date")
    errors[:base] << "Overlapping error: #{previously}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  
  validates :user_name, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token
  
  has_many :cats
  
  def self.find_by_credentials(user_name, password)
    user = User.find_by_user_name(user_name)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end
  
  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end
  
  private
  
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user
  
  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  def logout!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end
  
  def logged_in?
    !!current_user
  end
  
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :ensure_same_user, only: [:edit, :update]
  
  def index
    @cats = Cat.all
    render :index
  end
  
  def show
    @cat = Cat.find_by_id(params[:id])
    render :show
  end
  
  def new
    @cat = Cat.new()
    
    render :new
  end
  
  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id
    if @cat.save
      render :show
    else
      render(
        json: @cat.errors.full_messages, status: :unprocessable_entity
      )
    end
  end
  
  def edit
    #
    # @cat = current_user.cats.find(params[:id])
    render :edit
  end
  
  def update
    #
    # @cat = Cat.find_by_id(params[:id])
    
    if @cat.update_attributes(cat_params)
      render :json => @cat
    else 
      render( 
        :json => @cat.errors.full_messages, 
        :status => :unprocessable_entity 
      )
    end
  end
  
  private
  def cat_params
    params.require(:cat).permit(:name, :age, :color, :birth_date, :sex, :description)
  end
  
  def ensure_same_user
    @cat = Cat.find(params[:id])
    unless @cat.user_id == current_user.id
      flash[:errors] ||= [] << "This is not your cat!"
      redirect_to cat_url(@cat) #s_url
    end
    true
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :login_only_once, only: [:new, :create]
  
  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.find_by_credentials(
      params[:user][:user_name],
      params[:user][:password]
    )

    if @user.nil?
      @user = User.new(user_params)
      flash.now[:errors] ||= [] << "Credentials were wrong"
      render :new
    else
      session[:session_token] = @user.session_token
      flash[:notices] ||= [] << "Successfully logged in!"
      redirect_to cats_url
    end
  end
  
  def destroy
    logout!
    flash[:notices] ||= [] << "Successfully logged out!"
    redirect_to new_session_url
  end
  
  def login_only_once
    # logged in? go to index.
    redirect_to cats_url if logged_in? 
  end
  
  private
  
  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_only_once, only: [:new, :create]

  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notices] ||= [] << "Success!"
      session[:session_token] = @user.session_token
      redirect_to cats_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def login_only_once
    # logged in? go to cats index.
    redirect_to cats_url if logged_in? 
  end
  
  private
  
  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token_input
    "<input type='hidden'
           name='authenticity_token'
           value='#{form_authenticity_token }'>"
  end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cats/_form.html.erb
<% action_url = @cat.persisted? ? cat_url(@cat) : cats_url %>
<% form_method = @cat.persisted? ? "PATCH" : "POST" %>
<% submit_text = @cat.persisted? ? "Kitty update!" : "Who's the kitty?" %>

<form action="<%= action_url %>" method="POST">
  <%= render partial: "layouts/csrf" %>
  <input type="hidden" name="_method" value="<%= form_method %>">

  <label for="cat_name">Name:</label>
  <input type="text" name="cat[name]" id="cat_name" value="<%= @cat.name %>">
  <br>

  <label for="cat_age">Age:</label>
  <input type="text" name="cat[age]" id="cat_age" value="<%= @cat.age %>">
  <br>
  
  <input type="radio" name="cat[sex]" id="cat_sex_female" value="F"
    <%= "checked" if @cat.sex=="F" %> >
  <label for="cat_sex_female">Female</label>
  <input type="radio" name="cat[sex]" id="cat_sex_male" value="M"
    <%= "checked" if @cat.sex=="M" %> >
  <label for="cat_sex_male">Male</label>
  <br>
  
  <label for="cat_color">Color:</label>
    <!-- dropdown -->
    <select name="cat[color]" id="cat_color">
      <option value=""></option>
      <% Cat.colors.each do |color| %>
        <option value="<%= color %>"<%= "selected" if @cat.color==color %>><%= color %></option>
      <% end %>
    </select>
  <br>
    

  <label for="cat_birthdate">Birthdate:</label>
  <input type="date" name="cat[birth_date]" id="cat_birthdate" 
    value="<%= @cat.birth_date %>">
  <br>
  
  <label for="cat_description">Description:</label>
  <input type="textarea" name="cat[description]" id="cat_description" value="<%= @cat.description %>">
  <br>

  
  <input type="submit" value="<%= submit_text %>">

</form>

app/views/cats/edit.html.erb
<h1>Kitty update!</h1>

<%= render "form", cat: @cat %>
  

app/views/cats/index.html.erb
<h1>All the cats</h1>

<table>
  <thead>
    <tr>
      <th>Cat name:</th>
      <th>age:</th>
      <th>sex:</th>
      <th>color:</th>
    </tr>
  </thead>
  <tbody>
    <% @cats.each do |cat| %>
    <tr>
      <td><%= cat.name %></td>
      <td><%= cat.age %></td>
      <td><%= cat.sex=="F" ? "Female" : "Male" %></td>
      <td><%= cat.color.capitalize %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/cats/new.html.erb
<h1>Who's the kitty?</h1>

<%= render "form",  cat: @cat %>

app/views/cats/show.html.erb
<h1>Cat: <%= @cat.name %></h1>

<table>
  <thead>
    <tr>
      <th>Cat name:</th>
      <th>age:</th>
      <th>sex:</th>
      <th>color:</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @cat.name %></td>
      <td><%= @cat.age %></td>
      <td><%= @cat.sex=="F" ? "Female" : "Male" %></td>
      <td><%= @cat.color.capitalize %></td>
    </tr>
  </tbody>
</table>

<strong>Description:</strong>
<%= @cat.description %>

app/views/layouts/_csrf.html.erb
<input type="hidden"
       name="authenticity_token"
       value="<%= form_authenticity_token %>">

app/views/layouts/_errors.html.erb
<% if flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
    <%= error %><br />
  <% end %>
<% end%>

app/views/layouts/_sessions.html.erb
<% if !current_user.nil? %>
  <ul>
    <li>Logged in as: <%= current_user.user_name %></li>
    <li><%= button_to "Logout", session_url, method: :delete %></li>
  </ul>
<% else %>
  <ul>
    <li><%= button_to "Login", new_session_url, method: :get %></li>
  </ul>  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RentACat</title>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notices] %>
  <% flash[:notices].each do |msg| %>
    <%= msg %><br />
  <% end %>
<% end%>

<%= render partial: "layouts/sessions" %>
<%= render partial: "layouts/errors" %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Create new user login!</h1>

<%= render partial: "layouts/errors" %>

<form action="/user" method="post">
  <%= render partial: "layouts/csrf" %>
  
  <label for="user_user_name">Username</label>
  <input type="text" name="user[user_name]" id="user_user_name">
  <br>
  <label for="user_password">Password</label>
  <input type="password" name="user[password]" id="user_password">
  <br>
  <input type="submit" value="Make new user!">
</form>